### PR TITLE
Various macOS compilation and packaging fixes/backporting

### PR DESCRIPTION
**Pull request by traceon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Build/Testing/Packaging Improvement

### CODE REVIEW

**Comment by Enmk** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Review by Enmk — APPROVED** [review]
LGTM

**Pull request merged**
