### PR TITLE
Pre-release 21.8.15

### PR DESCRIPTION
**Pull request by Enmk**
Customizations

Applying 21.8 customizations for 21.8.15 release:
* Bug Fix: Fixed issue with merging configs that have <yandex> and <clickhouse> root XML tags. (backport of https://github.com/ClickHouse/ClickHouse/commit/213ecaedde9c5e5961ef6d809914efae241698f0) (via #114)
* Bug Fix: Backport of #31823 to 21.8: Fix invalid cast of nullable type when nullable primary key is used (via #110)
* Build/Testing/Packaging Improvement: Various macOS compilation and packaging fixes/backporting (via #108)

### CODE REVIEW

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by Enmk** [comment]
retrigger

**Comment by Enmk** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by zvonand** [comment]
retrigger

**Comment by Enmk** [comment]
https://altinity-test-reports.s3.amazonaws.com/builds/dev/v21.8.13-PR.122/x86_64/2022-04-13T06-07-54.032/report.html

### Integration
* There are only 3 failures: 2 are known flaky, 1 is environment configuration issue.

### Statefull
* No failures

### Stateless
* No failed tests other than xfailed 

### Stress Tests
* No failures

### Testflows Tests
* No failed tests other than xfailed 


### Unit test
* No failures

**Pull request merged**
