### PR TITLE
Fixed default root tag from <clickhouse> back to <yandex>

### PR DESCRIPTION
**Pull request by Enmk**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed default root tag from `<clickhouse>` back to `<yandex>` for configs generated on installation.
...

### CODE REVIEW

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by Enmk** [comment]
retrigger

**Pull request merged**
