### PR TITLE
Customizations/21.8

### PR DESCRIPTION
**Pull request by Enmk**
Customizations

Applying 21.8 customizations for 21.8.13 release
- Bug Fix: Fixed issue with merging configs that have <yandex> and <clickhouse> root XML tags. (backport of https://github.com/ClickHouse/ClickHouse/commit/213ecaedde9c5e5961ef6d809914efae241698f0) (via #114)

### CODE REVIEW

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by Enmk** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by sergio-h** [comment]
retrigger

**Comment by Enmk** [comment]
Retrigger

**Comment by Enmk** [comment]
retrigger

**Pull request closed without merging**
